swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints for transactions management.
  version: "1.0.0"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Fetch all transactions for the current month
      description: API to fetch all transactions grouped by account for the current month.
      parameters:
        - in: header
          name: Authorization
          description: Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "401":
          description: Unauthorized - Invalid or missing token
        "403":
          description: Forbidden - Access denied
        "500":
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Fetch details of a specific transaction
      description: API to fetch detailed information of a single transaction.
      parameters:
        - in: header
          name: Authorization
          description: Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized - Invalid or missing token
        "403":
          description: Forbidden - Access denied
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update a specific transaction
      description: API to update details of a transaction, such as category or notes.
      parameters:
        - in: header
          name: Authorization
          description: Bearer JWT token
          required: true
          type: string
        - in: path
          name: id
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Details to update for the transaction
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "401":
          description: Unauthorized - Invalid or missing token
        "403":
          description: Forbidden - Access denied (e.g., trying to update a transaction that doesn't belong to the user)
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

definitions:
  TransactionsResponse:
    type: object
    properties:
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier for the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        format: float
        description: Amount of the transaction
      balance:
        type: number
        format: float
        description: Balance after the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes for the transaction
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      notes:
        type: string
        description: Updated notes for the transaction
    required:
      - category
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
        description: HTTP status code
      message:
        type: string
        description: Response message
      body:
        type: object
